spring:
  mydatasource:
    myhikari:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      jdbc-url: jdbc:mysql://localhost:3306/news
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    hibernate:
      ddl-auto: create
#    properties:
#        hibernate.use-new-id-generator-mappings: true
#        hibernate.generate_statistics: true
#        hibernate.format_sql: true
#        hibernate.show9_sql: true
server:
  port: 8080
  servlet:
    context-path: /news